#!/usr/bin/env node
/* Runs after `expo export --platform web` (see the export:web script) and turns the exported
 * page into something you can add to a home screen and open without a connection:
 *
 *   - a black page before the script has loaded, instead of a white flash
 *   - a web manifest and icons, so "Add to Home Screen" gives a full-screen app
 *   - a small service worker: the app's own files are kept on the device, so it opens in a
 *     gym with no signal. Your data was already on the device; this covers the app itself.
 *   - vercel.json / _redirects so a static host answers every path with the app
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const APP = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const DIST = path.join(APP, 'dist')
const config = JSON.parse(fs.readFileSync(path.join(APP, 'app.json'), 'utf8')).expo
const indexFile = path.join(DIST, 'index.html')
if (!fs.existsSync(indexFile)) { console.error('dist/index.html not found — run `expo export --platform web` first'); process.exit(1) }

/* ---------- icons + manifest ---------- */

const icon = path.join(APP, 'assets', 'icon.png')
await sharp(icon).resize(192, 192).png().toFile(path.join(DIST, 'icon-192.png'))
await sharp(icon).resize(512, 512).png().toFile(path.join(DIST, 'icon-512.png'))
await sharp(icon).resize(180, 180).png().toFile(path.join(DIST, 'apple-touch-icon.png'))

fs.writeFileSync(path.join(DIST, 'manifest.webmanifest'), JSON.stringify({
  name: config.name,
  short_name: config.web?.shortName || config.name,
  description: config.web?.description || '',
  start_url: '/',
  scope: '/',
  display: 'standalone',
  orientation: 'portrait',
  background_color: '#000000',
  theme_color: '#000000',
  icons: [
    { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }
  ]
}, null, 2))

/* ---------- service worker ---------- */

// Everything the build shipped, so the first visit already has the whole app on the device.
const walk = dir => fs.readdirSync(dir, { withFileTypes: true }).flatMap(e =>
  e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)])
const shell = walk(DIST)
  .map(f => '/' + path.relative(DIST, f).split(path.sep).join('/'))
  .filter(f => !/\.(map|json)$/.test(f) && !['/sw.js', '/index.html', '/_redirects'].includes(f))
// The cache is named after the bundle, so a new release starts a clean one.
const bundle = shell.find(f => /\/entry-[0-9a-f]+\.js$/.test(f)) || String(Date.now())
const version = bundle.replace(/.*entry-([0-9a-f]+)\.js$/, '$1').slice(0, 12)

fs.writeFileSync(path.join(DIST, 'sw.js'), `// Generated by scripts/finish-web.mjs — do not edit.
const CACHE = 'evergreen-${version}'
const SHELL = ${JSON.stringify(['/', ...shell])}

self.addEventListener('install', event => {
  // One at a time and forgiving: a single file a host declines to serve must not cost the
  // whole offline copy, which is what cache.addAll does on any failure.
  event.waitUntil(
    caches.open(CACHE)
      .then(cache => Promise.all(SHELL.map(url => cache.add(url).catch(() => {}))))
      .then(() => self.skipWaiting())
  )
})

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k.startsWith('evergreen-') && k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  )
})

self.addEventListener('fetch', event => {
  const req = event.request
  const url = new URL(req.url)
  // Only this app's own files. Requests to a gym server (another origin) are never touched,
  // and neither is anything that is not a plain read.
  if (req.method !== 'GET' || url.origin !== self.location.origin) return

  if (req.mode === 'navigate') {
    // The page itself: the network first so a new release shows up, the kept copy offline.
    event.respondWith(
      fetch(req).then(res => {
        const copy = res.clone()
        caches.open(CACHE).then(cache => cache.put('/', copy))
        return res
      }).catch(() => caches.match('/'))
    )
    return
  }
  // Built files carry a hash in their name and never change: the kept copy is always right.
  event.respondWith(caches.match(req).then(hit => hit || fetch(req)))
})
`)

/* ---------- index.html ---------- */

let html = fs.readFileSync(indexFile, 'utf8')
const head = `
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <link rel="manifest" href="/manifest.webmanifest" />
    <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
    <link rel="icon" type="image/png" sizes="192x192" href="/icon-192.png" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="apple-mobile-web-app-title" content="${config.name}" />
    <meta name="color-scheme" content="dark" />
    <style>html, body, #root { background: #000; } body { margin: 0; -webkit-tap-highlight-color: transparent; }</style>
  </head>`
const boot = `
    <script>
      if ('serviceWorker' in navigator && (location.protocol === 'https:' || location.hostname === 'localhost')) {
        window.addEventListener('load', function () { navigator.serviceWorker && navigator.serviceWorker.register('/sw.js').catch(function () {}) })
      }
    </script>
  </body>`
if (!html.includes('manifest.webmanifest')) {
  html = html
    .replace(/\s*<meta name="viewport"[^>]*>/, '')
    .replace(/\s*<meta httpEquiv="X-UA-Compatible"[^>]*>/, '')
    .replace('</head>', '  ' + head.trimStart())
    .replace('</body>', '  ' + boot.trimStart())
  fs.writeFileSync(indexFile, html)
}

/* ---------- static-host rules ---------- */

// Every path that is not a file is the app (it routes in the browser). Hashed files are kept
// for a year; the page and the service worker are always asked for again.
fs.writeFileSync(path.join(DIST, 'vercel.json'), JSON.stringify({
  rewrites: [{ source: '/((?!_expo/|assets/|.*\\.[a-z0-9]+$).*)', destination: '/index.html' }],
  headers: [
    { source: '/_expo/static/(.*)', headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }] },
    { source: '/(sw.js|index.html|manifest.webmanifest)', headers: [{ key: 'Cache-Control', value: 'no-cache' }] },
    { source: '/(.*)', headers: [
      { key: 'X-Content-Type-Options', value: 'nosniff' },
      { key: 'X-Frame-Options', value: 'DENY' },
      { key: 'Referrer-Policy', value: 'same-origin' }
    ] }
  ]
}, null, 2))
fs.writeFileSync(path.join(DIST, '_redirects'), '/*  /index.html  200\n')   // Netlify, Cloudflare Pages

console.log(`web build finished: manifest, ${shell.length} files in the offline cache (${version}), host rules`)
